### ISSUE TITLE
Initialize Read Me file. 

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse-Presentation-Embed#1]
Create read-me file explaining the purpose of this repo. Add instructions on how to test the same.

**Comment by aryanbaburajan** [comment]
@satu0king Hi! I am Aryan Baburajan, 13 years old, beginner at JavaScript, Python, C++ and interested in working on this issue! So I was curious about your plan because the extension was empty and it currently directs the user to the official CircuitVerse website. Thanks! I'm also interested to work on the other two issues you opened!

**Comment by satu0king** [comment]
@aryanbaburajan welcome to CircuitVerse and open source :) The extension is empty because I just made it today to get started. 

Read https://github.com/CircuitVerse/CircuitVerse/issues/1704, maybe it will give an idea of what we are trying to do here. Looking forward to your contributions. Thanks!

**Comment by pawki07** [comment]
Hey, I would like to work on this issue. Please assign it to me.
